# Usa una imagen base de Ubuntu
FROM ubuntu:23.10

# Actualiza el sistema y instala una aplicación
RUN apt-get update && apt-get install -y nginx

# Expón el puerto 80 para que se pueda acceder a la aplicación
EXPOSE 80

# Comando de inicio de la aplicación
CMD ["nginx", "-g", "daemon off;"]